excerpt_separator: ""
pygments: ""
url: http://nicomedinap.github.io/cursos.html
title: Fotómetro
tagline: Interpretando luz de las estrellas
description: ""
paginate: 10
theme: jekyll-theme-cayman
highlighter: rouge
