excerpt_separator: ""
pygments: ""
url: http://nicomedinap.github.io/cursos.html
title: Cursos
tagline: experimentales
description: ""
paginate: 10
theme: jekyll-theme-cayman
highlighter: rouge
